### ISSUE TITLE
`scopes are not allowed` error without scopes

### ISSUE THREAD

**Issue by cengels** [KeisukeYamashita/commitlint-rs#278]
**Describe the bug**

Followup of #273. An input like `echo "feat: something" | commitlint` unexpectedly emits a `scopes are not allowed` error, even though a scope is not used in the commit message.

## Config

```yaml
rules:
  scope:
    level: error
    options: []
  scope-empty:
    level: ignore
```

## Error message

`scopes are not allowed`

## Expected behavior

No error.

## Version

```console
$ commitlint --version
commitlint-rs 0.1.8
```

## Additional context

Trying the same with `types.options: []` doesn't seem to work properly either, but let's be honest, permitting scopes but not types makes absolutely no sense at all, so I wouldn't really consider this a problem.
